services:
  app:
    image: egor051/buildcalc:latest
    container_name: buildcalc-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-https://buildcalc.online}
      - PORT=3000
      # - DATABASE_URL=${DATABASE_URL:-file:./prisma/dev.db}
    networks:
      - one-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  one-network:
    external: true
